services:

  redis-storage:
    image: redis
    volumes:
      - ./redis:/data

  mongodb:
    image: mongo
    restart: always
    ports:
      - ${MONGODB_PORT:-27017}:27017
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME:-library}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-password}
    volumes:
      - ./db/mongo:/data/db
      - ./initdb.d/:/docker-entrypoint-initdb.d/

  mongo_express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT:-8081}:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD:-password}
    depends_on:
      - mongodb

  ndse_library:
    image: andrew1gar/ndse-library
    environment:
      - PORT=80
      - COUNTER_URL=ndse_counter
      - DB_URL=mongodb://${DB_USERNAME:-root}:${DB_PASSWORD:-password}@mongodb:${MONGODB_PORT:-27017}/${DB_NAME:-library}
      - COOKIE_SECRET=${COOKIE_SECRET:-COOKIE_SECRET}
    ports:
      - ${LIBRARY_SERVICE_PORT:-3002}:80
    depends_on:
      - ndse_counter
      - mongodb

  ndse_counter:
    image: andrew1gar/ndse-counter
    environment:
      - PORT=80
      - REDIS_URL=redis://redis-storage
    ports:
      - ${COUNTER_SERVICE_PORT:-3003}:80
    depends_on:
      - redis-storage
